# Generated by Django 4.0.4 on 2022-06-07 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_otpmodel_otp_qr_alter_otpmodel_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpmodel",
            name="otp_qr",
        ),
    ]
