# Generated by Django 4.0.4 on 2022-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_otpmodel_otp_qr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpmodel",
            name="key",
            field=models.TextField(blank=True, unique=True),
        ),
    ]
