# Generated by Django 4.0.5 on 2022-07-09 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_otpmodel_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address_one",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address_two",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="otpmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otpmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="UserInformationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Phone Number"),
                ),
                ("address_one", models.CharField(blank=True, max_length=255)),
                ("address_two", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("zipcode", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="Country"),
                ),
                (
                    "profile_pic",
                    models.ImageField(default="users/default.png", upload_to="users/"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth Date"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Choose Gender",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_information",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
