# Generated by Django 4.0.5 on 2022-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_userinformationmodel_address_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformationmodel",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userinformationmodel",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="userinformationmodel",
            name="phone_number",
            field=models.CharField(max_length=50, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="userinformationmodel",
            name="zipcode",
            field=models.CharField(max_length=50),
        ),
    ]
