# Generated by Django 4.0.5 on 2022-07-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_userinformationmodel_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformationmodel",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Birth Date"),
        ),
    ]
