# Generated by Django 4.0.5 on 2022-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_userinformationmodel_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True, verbose_name="Email"),
        ),
    ]
