# Generated by Django 4.0.5 on 2022-07-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpmodel",
            name="key",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
