# Generated by Django 4.0.5 on 2022-10-20 21:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_remove_user_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
