# Generated by Django 4.2.4 on 2023-08-16 03:12

import uuid

import phonenumber_field.modelfields
from django.db import migrations, models

import helper.helper


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinformationmodel",
            old_name="is_active",
            new_name="status",
        ),
        migrations.AddField(
            model_name="otpmodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="otpmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100,
                unique=True,
                validators=[helper.helper.validate_email],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="userinformationmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="userinformationmodel",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone Number"
            ),
        ),
    ]
